name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
{%- if cookiecutter.version_management == "setuptools_scm" %}
      with:
        # setuptools_scm requires a non-shallow clone of the repository
        fetch-depth: 0
{%- endif %}

    - uses: actions/setup-python@v5
      name: Install Python

    - name: Build SDist
      run: pipx run build --sdist

    - uses: pypa/gh-action-pypi-publish@v1.8.11
